plugins {
    id "com.android.application"
}

android {
    namespace "dev.codex.voyahhud"
    compileSdk 35

    defaultConfig {
        applicationId "dev.codex.h53direct"
        minSdk 23
        targetSdk 28
        versionCode 57
        versionName "5.7"
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
}
